import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/lib/styles/globals.css";
import Header from "@/components/layout/Header";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full">
      <body className={`${pretendard.className} text-slate-900`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
